### PR TITLE
fix parsing of multiple directories in psr-4

### PR DESCRIPTION
**Pull request by sveneld**
Fix issue with parsing such block in composer.json
```
    "autoload": {
        "psr-4": {
            "Application\\": [
                "src/application",
                "src/applicationLegacy"
            ]
        }
    },
```

### CODE REVIEW

**Comment by sveneld** [comment]
@suin

**Comment by sveneld** [comment]
@suin please merge this pull request

**Comment by sveneld** [comment]
@suin can you make a new version tag for this fix?

**Comment by suin** [comment]
@sveneld I'm sorry for the delay. I have created a new version tag v2.3.0.

**Pull request merged**
